[metadata]
uuid = "d5ba0d3b-6762-4559-b0a5-fae11d41d447"
name = "外研版九上单词"
level = "九年级"
desc = "外研版九上单词"

[word.1]
text = "lady"
phonetic = "/ˈleɪdi/"
[word.1.para.n]
text = "女士，女子"

[word.2]
text = "gentleman"
phonetic = "/ˈdʒentlmən/"
[word.2.para.n]
text = "先生"

[word.3]
text = "high school"
[word.3.para.phr]
text = "高中"

[word.4]
text = "puppet"
phonetic = "/ˈpʌpɪt/"
[word.4.para.n]
text = "(牵线)木偶；布袋木偶，手偶"

[word.5]
text = "performer"
phonetic = "/pəˈfɔːmə/"
[word.5.para.n]
text = "表演者"

[word.6]
text = "finger"
phonetic = "/ˈfɪŋɡə/"
[word.6.para.n]
text = "手指"

[word.7]
text = "teenager"
phonetic = "/ˈtiːneɪdʒə/"
[word.7.para.n]
text = "青少年"

[word.8]
text = "old-fashioned"
phonetic = "/ˌəʊldˈfæʃənd/"
[word.8.para.adj]
text = "老式的，过时的"

[word.9]
text = "take part in"
[word.9.para.phr]
text = "参加，参与"

[word.10]
text = "performance"
phonetic = "/pəˈfɔːməns/"
[word.10.para.n]
text = "表演；演出"

[word.11]
text = "unless"
phonetic = "/ənˈles/"
[word.11.para.conj]
text = "除非……"

[word.12]
text = "video"
phonetic = "/ˈvɪdiəʊ/"
[word.12.para.n]
text = "视频"

[word.13]
text = "amaze"
phonetic = "/əˈmeɪz/"
[word.13.para.v]
text = "使大为惊奇"

[word.14]
text = "post"
phonetic = "/pəʊst/"
[word.14.para.v]
text = "发布"

[word.15]
text = "be flooded with"
[word.15.para.phr]
text = "大量收到"

[word.16]
text = "hold on"
[word.16.para.phr]
text = "坚持下去"

[word.17]
text = "blood"
phonetic = "/blʌd/"
[word.17.para.n]
text = "血，血液"

[word.18]
text = "interested"
phonetic = "/ˈɪntrəstɪd/"
[word.18.para.adj]
text = "感兴趣的"

[word.19]
text = "surprising"
phonetic = "/səˈpraɪzɪŋ/"
[word.19.para.adj]
text = "令人惊奇的，出人意料的"

[word.20]
text = "lost"
phonetic = "/lɒst/"
[word.20.para.adj]
text = "全神贯注的"

[word.21]
text = "viewer"
phonetic = "/ˈvjuːə/"
[word.21.para.n]
text = "观众"

[word.22]
text = "attention"
phonetic = "/əˈtenʃən/"
[word.22.para.n]
text = "注意"

[word.23]
text = "abroad"
phonetic = "/əˈbrɔːd/"
[word.23.para.adv]
text = "在国外"

[word.24]
text = "teenage"
phonetic = "/ˈtiːneɪdʒ/"
[word.24.para.adj]
text = "青少年的"

[word.25]
text = "folk arts"
[word.25.para.phr]
text = "民间艺术"

[word.26]
text = "programme"
phonetic = "/ˈprəʊɡræm/"
[word.26.para.n]
text = "计划，方案"

[word.27]
text = "volunteer"
phonetic = "/ˌvɒlənˈtɪə/"
[word.27.para.n]
text = "志愿者，义务工作者"

[word.28]
text = "group"
phonetic = "/ɡruːp/"
[word.28.para.n]
text = "组，群；团体"

[word.29]
text = "report"
phonetic = "/rɪˈpɔːt/"
[word.29.para.n]
text = "报道"

[word.30]
text = "fence"
phonetic = "/fens/"
[word.30.para.n]
text = "栅栏，围栏，篱笆"

[word.31]
text = "kill"
phonetic = "/kɪl/"
[word.31.para.v]
text = "弄死，杀死"

[word.32]
text = "scarecrow"
phonetic = "/ˈskeəkrəʊ/"
[word.32.para.n]
text = "稻草人"

[word.33]
text = "educator"
phonetic = "/ˈedʒukeɪtə/"
[word.33.para.n]
text = "教育家"

[word.34]
text = "country"
phonetic = "/ˈkʌntri/"
[word.34.para.n]
text = "国，国家"

[word.35]
text = "nation"
phonetic = "/ˈneɪʃən/"
[word.35.para.n]
text = "国家"

[word.36]
text = "shoulder the responsibility"
[word.36.para.phr]
text = "承担责任"

[word.37]
text = "energy"
phonetic = "/ˈenədʒi/"
[word.37.para.n]
text = "力量，活力"

[word.38]
text = "youth"
phonetic = "/juːθ/"
[word.38.para.n]
text = "青年，年轻人"

[word.39]
text = "wealthy"
phonetic = "/ˈwelθi/"
[word.39.para.adj]
text = "富有的，富裕的"

[word.40]
text = "independent"
phonetic = "/ˌɪndɪˈpendənt/"
[word.40.para.adj]
text = "独立的，自主的"

[word.41]
text = "excerpt"
phonetic = "/ˈeksɜːpt/"
[word.41.para.n]
text = "(书籍、诗歌、音乐等的)摘录，节录"

[word.42]
text = "tin"
phonetic = "/tɪn/"
[word.42.para.n]
text = "金属盒"

[word.43]
text = "spare"
phonetic = "/speə/"
[word.43.para.adj]
text = "备用的；多余的，闲置的"

[word.44]
text = "moneybox"
phonetic = "/ˈmʌnibɒks/"
[word.44.para.n]
text = "储钱盒，存钱罐"

[word.45]
text = "own"
phonetic = "/əʊn/"
[word.45.para.adj]
text = "自己的，属于自己的"

[word.46]
text = "size"
phonetic = "/saɪz/"
[word.46.para.n]
text = "大小，尺寸"

[word.47]
text = "better"
phonetic = "/ˈbetə/"
[word.47.para.adj]
text = "更好的，较好的"

[word.48]
text = "make sense"
[word.48.para.phr]
text = "解释得通；有道理"

[word.49]
text = "dreamland"
phonetic = "/ˈdriːmlænd/"
[word.49.para.n]
text = "梦境；理想世界"

[word.50]
text = "manage"
phonetic = "/ˈmænɪdʒ/"
[word.50.para.v]
text = "成功应付，得以对付过去"

[word.51]
text = "key"
phonetic = "/kiː/"
[word.51.para.n]
text = "关键"

[word.52]
text = "deal"
phonetic = "/diːl/"
[word.52.para.v]
text = "处理，应付，应对"

[word.53]
text = "deal with"
[word.53.para.phr]
text = "处理，应付，应对"

[word.54]
text = "laptop"
phonetic = "/ˈlæptɒp/"
[word.54.para.n]
text = "笔记本电脑"

[word.55]
text = "budget"
phonetic = "/ˈbʌdʒɪt/"
[word.55.para.n]
text = "预算"

[word.56]
text = "exactly"
phonetic = "/ɪɡˈzæktli/"
[word.56.para.adv]
text = "正是，不错"

[word.57]
text = "pleasure"
phonetic = "/ˈpleʒə/"
[word.57.para.n]
text = "愉快，快乐；满足"

[word.58]
text = "end"
phonetic = "/end/"
[word.58.para.n]
text = "最后部分，末尾"
[word.58.para.v]
text = "结束，停止"

[word.59]
text = "save"
phonetic = "/seɪv/"
[word.59.para.v]
text = "储蓄，存(钱)"

[word.60]
text = "bank"
phonetic = "/bæŋk/"
[word.60.para.n]
text = "银行"

[word.61]
text = "account"
phonetic = "/əˈkaʊnt/"
[word.61.para.n]
text = "账户"

[word.62]
text = "expensive"
phonetic = "/ɪkˈspensɪv/"
[word.62.para.adj]
text = "昂贵的"

[word.63]
text = "price"
phonetic = "/praɪs/"
[word.63.para.n]
text = "价格，价钱"

[word.64]
text = "savings"
phonetic = "/ˈseɪvɪŋz/"
[word.64.para.n]
text = "积蓄；银行存款"

[word.65]
text = "make ends meet"
[word.65.para.phr]
text = "使收支相抵，勉强维持生计"

[word.66]
text = "date"
phonetic = "/deɪt/"
[word.66.para.n]
text = "日期，日子"

[word.67]
text = "sale"
phonetic = "/seɪl/"
[word.67.para.n]
text = "出售，销售"

[word.68]
text = "on sale"
[word.68.para.phr]
text = "出售；廉价出售"

[word.69]
text = "T-shirt"
phonetic = "/ˈtiːʃɜːt/"
[word.69.para.n]
text = "T恤(衫)"

[word.70]
text = "website"
phonetic = "/ˈwebsaɪt/"
[word.70.para.n]
text = "网站"

[word.71]
text = "worth"
phonetic = "/wɜːθ/"
[word.71.para.adj]
text = "值……钱"

[word.72]
text = "dollar"
phonetic = "/ˈdɒlə/"
[word.72.para.n]
text = "美元"

[word.73]
text = "cent"
phonetic = "/sent/"
[word.73.para.n]
text = "分，美分"

[word.74]
text = "penny"
phonetic = "/ˈpeni/"
[word.74.para.n]
text = "一分钱硬币"

[word.75]
text = "couple"
phonetic = "/ˈkʌpəl/"
[word.75.para.n]
text = "一对夫妇；一对情侣"

[word.76]
text = "flat"
phonetic = "/flæt/"
[word.76.para.n]
text = "一套公寓房，单元房"

[word.77]
text = "treasure"
phonetic = "/ˈtreʒə/"
[word.77.para.n]
text = "珍宝，珍品"

[word.78]
text = "Christmas Eve"
[word.78.para.phr]
text = "圣诞前夕，平安夜"

[word.79]
text = "certainly"
phonetic = "/ˈsɜːtənli/"
[word.79.para.adv]
text = "当然"

[word.80]
text = "chain"
phonetic = "/tʃeɪn/"
[word.80.para.n]
text = "链子，链条"

[word.81]
text = "comb"
phonetic = "/kəʊm/"
[word.81.para.n]
text = "梳子"

[word.82]
text = "guest"
phonetic = "/ɡest/"
[word.82.para.n]
text = "嘉宾，宾客"

[word.83]
text = "remains"
phonetic = "/rɪˈmeɪnz/"
[word.83.para.n]
text = "遗迹"

[word.84]
text = "lie"
phonetic = "/laɪ/"
[word.84.para.v]
text = "位于"

[word.85]
text = "northwest"
phonetic = "/ˌnɔːθˈwest/"
[word.85.para.n]
text = "西北，西北方"

[word.86]
text = "such"
phonetic = "/sʌtʃ/"
[word.86.para.det]
text = "这样，如此(用于强调)"

[word.87]
text = "archaeologist"
phonetic = "/ˌɑːkiˈɒlədʒɪst/"
[word.87.para.n]
text = "考古学家"

[word.88]
text = "giant"
phonetic = "/ˈdʒaɪənt/"
[word.88.para.n]
text = "巨人"

[word.89]
text = "the fruit of"
[word.89.para.phr]
text = "……的成果"

[word.90]
text = "centre"
phonetic = "/ˈsentə/"
[word.90.para.n]
text = "中心"

[word.91]
text = "period"
phonetic = "/ˈpɪəriəd/"
[word.91.para.n]
text = "时期"

[word.92]
text = "form"
phonetic = "/fɔːm/"
[word.92.para.v]
text = "形成"

[word.93]
text = "valuable"
phonetic = "/ˈvæljuəbəl/"
[word.93.para.adj]
text = "宝贵的，有价值的"

[word.94]
text = "smoothly"
phonetic = "/ˈsmuːðli/"
[word.94.para.adv]
text = "顺利地(进行)"

[word.95]
text = "luck"
phonetic = "/lʌk/"
[word.95.para.n]
text = "好运，幸运"

[word.96]
text = "bring out"
[word.96.para.phr]
text = "使显现"

[word.97]
text = "cartoon"
phonetic = "/kɑːˈtuːn/"
[word.97.para.n]
text = "卡通(片)，动画片"

[word.98]
text = "silk"
phonetic = "/sɪlk/"
[word.98.para.n]
text = "丝绸"

[word.99]
text = "matchbox"
phonetic = "/ˈmætʃbɒks/"
[word.99.para.n]
text = "火柴盒"

[word.100]
text = "weight"
phonetic = "/weɪt/"
[word.100.para.n]
text = "重量，分量"

[word.101]
text = "around"
phonetic = "/əˈraʊnd/"
[word.101.para.adv]
text = "大约"

[word.102]
text = "ton"
phonetic = "/tʌn/"
[word.102.para.n]
text = "英吨"

[word.103]
text = "mystery"
phonetic = "/ˈmɪstəri/"
[word.103.para.n]
text = "神秘事物，谜"

[word.104]
text = "coast"
phonetic = "/kəʊst/"
[word.104.para.n]
text = "海岸，海滨"

[word.105]
text = "pretty"
phonetic = "/ˈprɪti/"
[word.105.para.adj]
text = "漂亮的，标致的"

[word.106]
text = "hit"
phonetic = "/hɪt/"
[word.106.para.n]
text = "风行一时的事物"

[word.107]
text = "besides"
phonetic = "/bɪˈsaɪdz/"
[word.107.para.prep]
text = "除……之外(还)"

[word.108]
text = "creativity"
phonetic = "/ˌkriːeɪˈtɪvəti/"
[word.108.para.n]
text = "独创性，创造力"

[word.109]
text = "come to life"
[word.109.para.phr]
text = "变得生动"

[word.110]
text = "technology"
phonetic = "/tekˈnɒlədʒi/"
[word.110.para.n]
text = "技术"

[word.111]
text = "multimedia"
phonetic = "/ˌmʌltiˈmiːdiə/"
[word.111.para.adj]
text = "多媒体的"

[word.112]
text = "noisy"
phonetic = "/ˈnɔɪzi/"
[word.112.para.adj]
text = "嘈杂的"

[word.113]
text = "collection"
phonetic = "/kəˈlekʃən/"
[word.113.para.n]
text = "(一批)收藏品"

[word.114]
text = "fever"
phonetic = "/ˈfiːvə/"
[word.114.para.n]
text = "狂热，亢奋"

[word.115]
text = "pride"
phonetic = "/praɪd/"
[word.115.para.n]
text = "自豪，骄傲"

[word.116]
text = "take pride in"
[word.116.para.phr]
text = "对……感到自豪"

[word.117]
text = "design"
phonetic = "/dɪˈzaɪn/"
[word.117.para.n]
text = "装饰图案"

[word.118]
text = "bat"
phonetic = "/bæt/"
[word.118.para.n]
text = "蝙蝠"

[word.119]
text = "scarf"
phonetic = "/skɑːf/"
[word.119.para.n]
text = "围巾；披肩"

[word.120]
text = "fridge"
phonetic = "/frɪdʒ/"
[word.120.para.n]
text = "冰箱，冰柜"

[word.121]
text = "fridge magnet"
[word.121.para.phr]
text = "冰箱磁贴"

[word.122]
text = "mirror"
phonetic = "/ˈmɪrə/"
[word.122.para.v]
text = "反映"

[word.123]
text = "great-aunt"
phonetic = "/ˌɡreɪtˈɑːnt/"
[word.123.para.n]
text = "舅婆；姑婆；姨婆；叔祖母"

[word.124]
text = "person"
phonetic = "/ˈpɜːsən/"
[word.124.para.n]
text = "人"

[word.125]
text = "fighter"
phonetic = "/ˈfaɪtə/"
[word.125.para.n]
text = "斗士，奋斗者"

[word.126]
text = "later"
phonetic = "/ˈleɪtə/"
[word.126.para.adv]
text = "之后"

[word.127]
text = "footstep"
phonetic = "/ˈfʊtstep/"
[word.127.para.n]
text = "足迹"

[word.128]
text = "name... after"
[word.128.para.phr]
text = "以……的名字命名"

[word.129]
text = "realise"
phonetic = "/ˈriːəlaɪz/"
[word.129.para.v]
text = "明白；认识到"

[word.130]
text = "could"
phonetic = "/kʊd/"
[word.130.para.aux]
text = "能，可以"

[word.131]
text = "leave... behind"
[word.131.para.phr]
text = "离开，丢下"

[word.132]
text = "gentle"
phonetic = "/ˈdʒentl/"
[word.132.para.adj]
text = "温和的，温柔的"

[word.133]
text = "pity"
phonetic = "/ˈpɪti/"
[word.133.para.n]
text = "可惜，遗憾"

[word.134]
text = "war"
phonetic = "/wɔː/"
[word.134.para.n]
text = "战争"

[word.135]
text = "battle"
phonetic = "/ˈbætl/"
[word.135.para.n]
text = "战斗，战役"

[word.136]
text = "shock"
phonetic = "/ʃɒk/"
[word.136.para.n]
text = "令人震惊的事"

[word.137]
text = "survivor"
phonetic = "/səˈvaɪvə/"
[word.137.para.n]
text = "生还者，幸存者"

[word.138]
text = "temperature"
phonetic = "/ˈtemprətʃə/"
[word.138.para.n]
text = "温度，气温"

[word.139]
text = "post"
phonetic = "/pəʊst/"
[word.139.para.n]
text = "岗位"

[word.140]
text = "front line"
[word.140.para.phr]
text = "前线"

[word.141]
text = "lose"
phonetic = "/luːz/"
[word.141.para.v]
text = "丧失，失去"

[word.142]
text = "deeply"
phonetic = "/ˈdiːpli/"
[word.142.para.adv]
text = "非常，深入地"

[word.143]
text = "presenter"
phonetic = "/prɪˈzentə/"
[word.143.para.n]
text = "主持人，主播"

[word.144]
text = "recommend"
phonetic = "/ˌrekəˈmend/"
[word.144.para.v]
text = "推荐"

[word.145]
text = "co-pilot"
phonetic = "/ˈkəʊˌpaɪlət/"
[word.145.para.n]
text = "(飞机)副驾驶员"

[word.146]
text = "engine"
phonetic = "/ˈendʒɪn/"
[word.146.para.n]
text = "发动机，引擎"

[word.147]
text = "state"
phonetic = "/steɪt/"
[word.147.para.v]
text = "陈述；说明"

[word.148]
text = "dreamer"
phonetic = "/ˈdriːmə/"
[word.148.para.n]
text = "做梦的人"

[word.149]
text = "pick"
phonetic = "/pɪk/"
[word.149.para.v]
text = "采，摘"

[word.150]
text = "countless"
phonetic = "/ˈkaʊntləs/"
[word.150.para.adj]
text = "无数的"

[word.151]
text = "thing"
phonetic = "/θɪŋ/"
[word.151.para.n]
text = "东西，物"

[word.152]
text = "experiment"
phonetic = "/ɪkˈsperəmənt/"
[word.152.para.n]
text = "实验"

[word.153]
text = "scientific research"
[word.153.para.phr]
text = "科学研究"

[word.154]
text = "type"
phonetic = "/taɪp/"
[word.154.para.n]
text = "类型，种类"

[word.155]
text = "poor"
phonetic = "/pɔː/"
[word.155.para.adj]
text = "差的，不佳的"

[word.156]
text = "soil"
phonetic = "/sɔɪl/"
[word.156.para.n]
text = "土壤，泥土"

[word.157]
text = "feed"
phonetic = "/fiːd/"
[word.157.para.v]
text = "养活"

[word.158]
text = "pass away"
[word.158.para.phr]
text = "过世，离世"

[word.159]
text = "socialist"
phonetic = "/ˈsəʊʃəlɪst/"
[word.159.para.adj]
text = "社会主义的"

[word.160]
text = "human"
phonetic = "/ˈhjuːmən/"
[word.160.para.adj]
text = "人的，人类的"

[word.161]
text = "drop"
phonetic = "/drɒp/"
[word.161.para.v]
text = "降低"

[word.162]
text = "tourist"
phonetic = "/ˈtʊərɪst/"
[word.162.para.n]
text = "游客"

[word.163]
text = "benefit"
phonetic = "/ˈbenəfɪt/"
[word.163.para.v]
text = "受益，得益"

[word.164]
text = "wonder"
phonetic = "/ˈwʌndə/"
[word.164.para.n]
text = "奇迹，奇观"

[word.165]
text = "once again"
[word.165.para.phr]
text = "再一次"

[word.166]
text = "admire"
phonetic = "/ədˈmaɪə/"
[word.166.para.v]
text = "欣赏，观赏"

[word.167]
text = "throughout"
phonetic = "/θruːˈaʊt/"
[word.167.para.prep]
text = "在整个期间，自始至终"

[word.168]
text = "mark"
phonetic = "/mɑːk/"
[word.168.para.n]
text = "痕迹；标记"

[word.169]
text = "rapid"
phonetic = "/ˈræpɪd/"
[word.169.para.adj]
text = "快速的"

[word.170]
text = "society"
phonetic = "/səˈsaɪti/"
[word.170.para.n]
text = "社会"

[word.171]
text = "cancel"
phonetic = "/ˈkænsəl/"
[word.171.para.v]
text = "取消"

[word.172]
text = "start over"
[word.172.para.phr]
text = "重新开始"

[word.173]
text = "get along with"
[word.173.para.phr]
text = "与……相处融洽"

[word.174]
text = "permit"
phonetic = "/pəˈmɪt/"
[word.174.para.v]
text = "允许"

[word.175]
text = "affect"
phonetic = "/əˈfekt/"
[word.175.para.v]
text = "影响"

[word.176]
text = "organisation"
phonetic = "/ˌɔːɡənaɪˈzeɪʃən/"
[word.176.para.n]
text = "组织，机构"

[word.177]
text = "harm"
phonetic = "/hɑːm/"
[word.177.para.v]
text = "伤害"

[word.178]
text = "punish"
phonetic = "/ˈpʌnɪʃ/"
[word.178.para.v]
text = "处罚，惩罚"

[word.179]
text = "global warming"
[word.179.para.phr]
text = "全球变暖"

[word.180]
text = "rubbish"
phonetic = "/ˈrʌbɪʃ/"
[word.180.para.n]
text = "垃圾"

[word.181]
text = "overfish"
phonetic = "/ˌəʊvəˈfɪʃ/"
[word.181.para.v]
text = "过度捕捞"

[word.182]
text = "gas"
phonetic = "/ɡæs/"
[word.182.para.n]
text = "气，气体"

[word.183]
text = "greenhouse gas"
[word.183.para.phr]
text = "温室气体"

[word.184]
text = "square"
phonetic = "/skweə/"
[word.184.para.adj]
text = "平方的"

[word.185]
text = "logging"
phonetic = "/ˈlɒɡɪŋ/"
[word.185.para.n]
text = "伐木"

[word.186]
text = "solar panel"
[word.186.para.phr]
text = "太阳能电池板"

[word.187]
text = "microphone"
phonetic = "/ˈmaɪkrəfəʊn/"
[word.187.para.n]
text = "麦克风，话筒"

[word.188]
text = "alarm"
phonetic = "/əˈlɑːm/"
[word.188.para.n]
text = "警报"

[word.189]
text = "guard"
phonetic = "/ɡɑːd/"
[word.189.para.n]
text = "警卫；门卫"

[word.190]
text = "foreigner"
phonetic = "/ˈfɒrənə/"
[word.190.para.n]
text = "外国人"

[word.191]
text = "logo"
phonetic = "/ˈləʊɡəʊ/"
[word.191.para.n]
text = "标识，徽标"

[word.192]
text = "endangered"
phonetic = "/ɪnˈdeɪndʒəd/"
[word.192.para.adj]
text = "濒危的"

[word.193]
text = "vulnerable"
phonetic = "/ˈvʌlnərəbəl/"
[word.193.para.adj]
text = "易受伤的"

[word.194]
text = "protection"
phonetic = "/prəˈtekʃən/"
[word.194.para.n]
text = "保护"

[word.195]
text = "farmland"
phonetic = "/ˈfɑːmlænd/"
[word.195.para.n]
text = "农田，耕地"

[word.196]
text = "consider"
phonetic = "/kənˈsɪdə/"
[word.196.para.v]
text = "认为"

[word.197]
text = "material"
phonetic = "/məˈtɪəriəl/"
[word.197.para.n]
text = "材料"

[word.198]
text = "shape"
phonetic = "/ʃeɪp/"
[word.198.para.v]
text = "使成形"

[word.199]
text = "long-lasting"
phonetic = "/ˌlɒŋˈlɑːstɪŋ/"
[word.199.para.adj]
text = "耐用的"

[word.200]
text = "cheap"
phonetic = "/tʃiːp/"
[word.200.para.adj]
text = "便宜的"

[word.201]
text = "environmental"
phonetic = "/ɪnˌvaɪrənˈmentl/"
[word.201.para.adj]
text = "环境的"

[word.202]
text = "toothbrush"
phonetic = "/ˈtuːθbrʌʃ/"
[word.202.para.n]
text = "牙刷"

[word.203]
text = "glove"
phonetic = "/ɡlʌv/"
[word.203.para.n]
text = "手套"

[word.204]
text = "former"
phonetic = "/ˈfɔːmə/"
[word.204.para.adj]
text = "以前的"

[word.205]
text = "wing"
phonetic = "/wɪŋ/"
[word.205.para.n]
text = "翅膀，翼"

[word.206]
text = "tie"
phonetic = "/taɪ/"
[word.206.para.v]
text = "系，扎，拴"

[word.207]
text = "stuck"
phonetic = "/stʌk/"
[word.207.para.adj]
text = "卡住的，动不了的"

[word.208]
text = "bin"
phonetic = "/bɪn/"
[word.208.para.n]
text = "箱；垃圾箱"

[word.209]
text = "mistake... for..."
[word.209.para.phr]
text = "把……错当成"

[word.210]
text = "average"
phonetic = "/ˈævərɪdʒ/"
[word.210.para.n]
text = "平均数"

[word.211]
text = "on average"
[word.211.para.phr]
text = "平均来看"

[word.212]
text = "gram"
phonetic = "/ɡræm/"
[word.212.para.n]
text = "克"

[word.213]
text = "tiny"
phonetic = "/ˈtaɪni/"
[word.213.para.adj]
text = "极小的"

[word.214]
text = "break down"
[word.214.para.phr]
text = "分解"

[word.215]
text = "trouble"
phonetic = "/ˈtrʌbəl/"
[word.215.para.n]
text = "麻烦，问题"

[word.216]
text = "wisely"
phonetic = "/ˈwaɪzli/"
[word.216.para.adv]
text = "明智地"

[word.217]
text = "highlight"
phonetic = "/ˈhaɪlaɪt/"
[word.217.para.v]
text = "突出，强调"

[word.218]
text = "pollute"
phonetic = "/pəˈluːt/"
[word.218.para.v]
text = "污染"

[word.219]
text = "electronic"
phonetic = "/ɪˌlekˈtrɒnɪk/"
[word.219.para.adj]
text = "电子的"

[word.220]
text = "truck"
phonetic = "/trʌk/"
[word.220.para.n]
text = "货车，卡车"

[word.221]
text = "emission"
phonetic = "/ɪˈmɪʃən/"
[word.221.para.n]
text = "排放物"

[word.222]
text = "upcycle"
phonetic = "/ˈʌpˌsaɪkəl/"
[word.222.para.v]
text = "升级改造"

[word.223]
text = "reuse"
phonetic = "/ˌriːˈjuːz/"
[word.223.para.v]
text = "再使用"

[word.224]
text = "fox"
phonetic = "/fɒks/"
[word.224.para.n]
text = "狐狸"

[word.225]
text = "loudly"
phonetic = "/ˈlaʊdli/"
[word.225.para.adv]
text = "响亮地"

[word.226]
text = "land"
phonetic = "/lænd/"
[word.226.para.v]
text = "掉落"

[word.227]
text = "village"
phonetic = "/ˈvɪlɪdʒ/"
[word.227.para.n]
text = "乡村，村庄"

[word.228]
text = "reporter"
phonetic = "/rɪˈpɔːtə/"
[word.228.para.n]
text = "记者"

[word.229]
text = "depth"
phonetic = "/depθ/"
[word.229.para.n]
text = "深，深度"

[word.230]
text = "suggest"
phonetic = "/səˈdʒest/"
[word.230.para.v]
text = "建议，提议"

[word.231]
text = "businessman"
phonetic = "/ˈbɪznəsmən/"
[word.231.para.n]
text = "商人；企业家"

[word.232]
text = "industrial"
phonetic = "/ɪnˈdʌstriəl/"
[word.232.para.adj]
text = "工业的"

[word.233]
text = "litter"
phonetic = "/ˈlɪtə/"
[word.233.para.n]
text = "垃圾，废弃物"

[word.234]
text = "peace"
phonetic = "/piːs/"
[word.234.para.n]
text = "和平；平静"

[word.235]
text = "business"
phonetic = "/ˈbɪznəs/"
[word.235.para.n]
text = "公司，企业"

[word.236]
text = "building"
phonetic = "/ˈbɪldɪŋ/"
[word.236.para.n]
text = "建筑物；楼房"

[word.237]
text = "imagination"
phonetic = "/ɪˌmædʒəˈneɪʃən/"
[word.237.para.n]
text = "幻想"
